services:
  - type: web
    name: laravel-app
    env: docker
    plan: starter
    buildCommand: |
      cp nginx.conf /etc/nginx/conf.d/default.conf
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: |
      php-fpm -D
      nginx -g 'daemon off;'
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://yourapp.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: laravel-mysql
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-mysql
          property: password

databases:
  - name: laravel-mysql
    plan: free
